[project]
name = "audio_proc"
version = "0.1.0"

[tool.pyodide-build]
packages = ["audio_proc"]

[build-system]
requires = ["setuptools>=61.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"
