[project]
name = "image_processing"
version = "0.1.0"

[tool.pyodide-build]
packages = ["image_processing"]

[build-system]
requires = ["setuptools>=61.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"
